apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  namespace: registry
data:
  config.yml: |
    version: 0.1
    log:
        fields:
            service: registry
    http:
        addr: :5000
    storage:
        cache:
            layerinfo: inmemory
        s3:
            region: us-east-1
            regionendpoint: http://minio.fava.casa:9000
            bucket: registry
            encrypt: false
            secure: false
            v4auth: true
            chunksize: 5242880
            rootdirectory: /
