apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  namespace: registry
data:
  config.yml: |
    version: 0.1
    log:
      level: info
    storage:
      s3:
        accesskey: ${REGISTRY_STORAGE_S3_ACCESSKEY}
        secretkey: ${REGISTRY_STORAGE_S3_SECRETKEY}
        region: us-east-1
        bucket: registry
        regionendpoint: http://minio.my.home.lan:9000
        secure: false
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
